In [17]:
#convert a matrix 2Dto3D
B = np.ones((5,5))
print(B[:,:,None])

[[[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]
  [ 1.]
  [ 1.]]]


In [25]:
#reshape given matrix
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[4,0]]
print(A)

[[20 21 22 23 24]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [70]:
#compute the rank of a matrix 
np.linalg.matrix_rank(np.eye(3))

3

In [41]:
#singular value decomposition (svd)
A = np.random.uniform(0, 1, (10, 10))
U, S, V = np.linalg.svd(A)

print("A: ", A)
print("U: ", U)
print("S: ", S)
print("V: ", V)

('A: ', array([[ 0.73655795,  0.4681471 ,  0.17693048,  0.59930799,  0.67516164,
         0.79380152,  0.04453619,  0.36939126,  0.77942014,  0.19424623],
       [ 0.94860373,  0.10349495,  0.76784369,  0.69847983,  0.41327949,
         0.00606052,  0.16776741,  0.53754909,  0.72342454,  0.55793002],
       [ 0.36772012,  0.43301448,  0.72639425,  0.41143061,  0.79216304,
         0.6416648 ,  0.73150139,  0.73992587,  0.04132919,  0.35267834],
       [ 0.56324653,  0.63311003,  0.5447252 ,  0.3302595 ,  0.87619416,
         0.20537085,  0.03856296,  0.70725536,  0.21296997,  0.78563833],
       [ 0.07431265,  0.72695193,  0.19176885,  0.69515779,  0.2890577 ,
         0.31978169,  0.07502654,  0.75573987,  0.36302052,  0.88566457],
       [ 0.13374274,  0.31804798,  0.80141221,  0.97943873,  0.98806396,
         0.98514285,  0.49443641,  0.66369551,  0.21100643,  0.42701035],
       [ 0.25951662,  0.24934146,  0.62431412,  0.2652848 ,  0.84462786,
         0.58661375,  0.85266359,  0.

In [46]:
#compute the qr factorization of a matrix
A = np.random.uniform(0,1,(10,10))
Q, R = np.linalg.qr(A)

print("A: ", A)
print("Q: ", Q)
print("R: ", R)

np.allclose(A, np.dot(Q, R))#check A does equal to QR

('A: ', array([[ 0.68720536,  0.38112629,  0.1587699 ,  0.68940361,  0.65935596,
         0.89060681,  0.39758638,  0.03922142,  0.15476079,  0.04668527],
       [ 0.84460315,  0.23017371,  0.46284491,  0.22726943,  0.31417634,
         0.70707872,  0.61864418,  0.73000649,  0.85653635,  0.81988555],
       [ 0.04464876,  0.1739488 ,  0.46714857,  0.94667179,  0.16887441,
         0.82071329,  0.16166356,  0.70719095,  0.04751358,  0.07307259],
       [ 0.07901927,  0.92509211,  0.14084202,  0.61628249,  0.84079076,
         0.67606173,  0.66166137,  0.84645427,  0.26756786,  0.18046361],
       [ 0.67997578,  0.88313097,  0.80113593,  0.10074678,  0.08160054,
         0.94084758,  0.97737399,  0.2253518 ,  0.0504833 ,  0.15510345],
       [ 0.98651313,  0.7188449 ,  0.83009622,  0.1907018 ,  0.07300056,
         0.72243005,  0.8532045 ,  0.34760555,  0.61899824,  0.75794898],
       [ 0.01898303,  0.68536131,  0.28096413,  0.38348236,  0.4777759 ,
         0.88200345,  0.50179064,  0.

In [69]:
#determinant of a matrix
A = np.random.uniform(1,5,(3,3))
np.linalg.det(A)

4.1884686748839997

In [84]:
#a basic linear regression example 
import numpy as np
import matplotlib.pylab as plt

x_i = np.arange(0,10)
A = np.array([x_i, np.ones(10)])
y_i = x_i**2
w = np.linalg.lstsq(A.T, y_i)[0]

lin_func = w[0]*x_i + w[1]

plt.plot(x_i, lin_func, 'b-', x_i, y_i, 'ro')
plt.xlabel('x-values')
plt.ylabel('y-values')
plt.show()

ValueError: operands could not be broadcast together with shapes (2,) (10,) 

In [104]:
#compute a Moore-Penrose Pseudoinverse
A = np.random.uniform(1,10,(5,5))
inv_A = np.linalg.inv(A)
pinv_A = np.dot(np.linalg.inv(np.dot(A.T,A)),A.T)
pinv_A2 = np.linalg.pinv(A) 

print("A: ", A)
print("inverse of A: ", inv_A)
print("pseudo inverse of A with Naive method: ", pinv_A)
print("pseudo inverse of A: ", pinv_A2)

np.allclose(pinv_A, pinv_A2)#check inverses of a matrix A

('A: ', array([[ 1.76711743,  8.7022906 ,  2.11264333,  3.02654917,  6.25591759],
       [ 8.04829739,  1.41965248,  7.44826203,  8.40809406,  2.87403881],
       [ 1.44644595,  3.18446194,  7.08122586,  9.88159976,  1.15080679],
       [ 1.87443319,  8.38816034,  5.76992923,  1.32944074,  3.65567619],
       [ 3.40430127,  6.18414536,  9.74011309,  3.76061619,  2.31465982]]))
('inverse of A: ', array([[-0.31666794,  0.25766838, -0.01740942,  0.66900107, -0.51200474],
       [-0.3761109 ,  0.12122737,  0.13824399,  0.92090152, -0.6571606 ],
       [ 0.19803817, -0.13193535, -0.08334124, -0.5584614 ,  0.5520209 ],
       [-0.05990645,  0.0431178 ,  0.14567138,  0.16396876, -0.2230171 ],
       [ 0.73459114, -0.21772217, -0.22971629, -1.36072537,  0.98024372]]))
('pseudo inverse of A with Naive method: ', array([[-0.31666794,  0.25766838, -0.01740942,  0.66900107, -0.51200474],
       [-0.3761109 ,  0.12122737,  0.13824399,  0.92090152, -0.6571606 ],
       [ 0.19803817, -0.13193535, -0.

True