In [50]:
# Name: Gonul AYCI
# Date: Bogazici University, Mar. 2017

#This document is prepared for only practicing
#Some of examples are from:
#http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html

#Import the numpy package under the name np
#When you write next line, you need to run this cell before using np
import numpy as np

#Print the numpy version and the configuration
print(np.__version__)
np.show_config

#Create a null vector of size 10 and its transpoze
a = np.zeros(10)
print(a)

b = np.array([[1, 2], [3, 4]])
print(b)
print("transpose of b matrix: ", b.transpose())

#Create a unit vector of size 10 but the third value which is 0
c = np.ones(10)
c[2] = 0
print(c)

#Create a vector with values ranging from 5 to 19
d = np.arange(5,20)
print(d)

#Reverse a vector (first element becomes last)
e = np.arange(20)
e = e[:4:-1]
print("reverse: ", e)

#Create a 3x3 matrix with values ranging from 0 to 8
f = np.arange(9).reshape(3,3)
print(f)

#Find indices of non-zero elements from [1,2,0,0,4,-3]
g = np.nonzero([1,2,0,0,4,-3])
print("nonzero: ", g)

#Create a 3x3 identity matrix 
h = np.eye(3)
print("identity matrix: ", h)

#Create a 2x2 array with random values
i = np.random.random((2,2))
print(i)

#Create a 10x10 array with random values and find the minimum and maximum values
j = np.random.random((10,10))
jMax, jMin = j.max(), j.min()
print("Max: ", jMax, "Min: ", jMin)

#Create a random vector of size 30 and find the mean, variance, and standart deviation values
k = np.random.random(30)
kMean, kVar, kStd = k.mean(), np.var(k), np.std(k)
print("mean: ", kMean, "variance: ", kVar, "standart deviation: ", kStd)

#Create a 2d array with 1 on the border and 0 inside
l = np.ones((10,10))
l[1:-1,1:-1] = 0
print(l)

#Create a 5x5 matrix with values 1,2,3,4 on the diagonal
m = np.diag(1 + np.arange(5), k = 0)
print(m)

#Create a 8x8 matrix and fill it with a checkerboard pattern
n = np.zeros((8,8), dtype=int)
n[1::2, ::2] = 1
n[::2, 1::2] = 1
print(n)

#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
print(np.unravel_index(100, (6,7,8)))

1.11.3
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[1 2]
 [3 4]]
('transpose of b matrix: ', array([[1, 3],
       [2, 4]]))
[ 1.  1.  0.  1.  1.  1.  1.  1.  1.  1.]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
('reverse: ', array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5]))
[[0 1 2]
 [3 4 5]
 [6 7 8]]
('nonzero: ', (array([0, 1, 4, 5]),))
('identity matrix: ', array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]]))
[[ 0.46400369  0.73582127]
 [ 0.90643947  0.62476208]]
('Max: ', 0.99184601935056671, 'Min: ', 9.5963913786412114e-05)
('mean: ', 0.53224773049173768, 'variance: ', 0.0819540513706499, 'standart deviation: ', 0.28627618023623602)
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  