In [17]:
# Name: Gonul AYCI
# Date: Bogazici University, Mar. 2017

#This document is prepared for only practicing
#Many thanks to Nicolas P. Rougier for most of exercises.
#https://github.com/rougier/numpy-100
#http://www.labri.fr/perso/nrougier/teaching/numpy.100/index.html
#Some of exercises and modifications belong to me.

#Import the numpy package under the name np
#When you write next line, you need to run this cell before using np
import numpy as np

#Print the numpy version and the configuration
print(np.__version__)
np.show_config

#Create a null vector of size 10 and its transpoze
a = np.zeros(10)
print(a)

b = np.array([[1, 2], [3, 4]])
print(b)
print("transpose of b matrix: ", b.transpose())

#Create a unit vector of size 10 but the third value which is 0
c = np.ones(10)
c[2] = 0
print(c)

#Create a vector with values ranging from 5 to 19
d = np.arange(5,20)
print(d)

#Reverse a vector (first element becomes last)
e = np.arange(20)
e = e[:4:-1]
print("reverse: ", e)

#Create a 3x3 matrix with values ranging from 0 to 8
f = np.arange(9).reshape(3,3)
print(f)

#Find indices of non-zero elements from [1,2,0,0,4,-3]
g = np.nonzero([1,2,0,0,4,-3])
print("nonzero: ", g)

#Create a 3x3 identity matrix 
h = np.eye(3)
print("identity matrix: ", h)

#Create a 2x2 array with random values
i = np.random.random((2,2))
print(i)

#Create a 10x10 array with random values and find the minimum and maximum values
j = np.random.random((10,10))
jMax, jMin = j.max(), j.min()
print("Max: ", jMax, "Min: ", jMin)

#Create a random vector of size 30 and find the mean, variance, and standart deviation values
k = np.random.random(30)
kMean, kVar, kStd = k.mean(), k.var(), k.std()
print("mean: ", kMean, "variance: ", kVar, "standart deviation: ", kStd)

#Create a 2d array with 1 on the border and 0 inside
l = np.ones((10,10))
l[1:-1,1:-1] = 0
print(l)

#Create a 5x5 matrix with values 1,2,3,4 on the diagonal
m = np.diag(1 + np.arange(5), k = 0)
print(m)

#Create a 8x8 matrix and fill it with a checkerboard pattern
n = np.zeros((8,8), dtype=int)
n[1::2, ::2] = 1
n[::2, 1::2] = 1
print('''checkerboard: ''', n)

#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
print(np.unravel_index(100, (6,7,8)))

#Create a matrix which include repeated elements
o = np.array([[3,4,5], [6,7,8]])
np.tile(o, (2,2))

#Create a checkerboard 8x8 matrix using the tile function
p = np.tile(np.array([[0,1], [1,0]]) , (4,4))
print('checkerboard with tile function:', p)

1.12.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[1 2]
 [3 4]]
transpose of b matrix:  [[1 3]
 [2 4]]
[ 1.  1.  0.  1.  1.  1.  1.  1.  1.  1.]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
reverse:  [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
nonzero:  (array([0, 1, 4, 5]),)
identity matrix:  [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.88201627  0.21179709]
 [ 0.25344864  0.50806944]]
Max:  0.993046072455 Min:  7.33217689612e-05
mean:  0.465324766623 variance:  0.067448169855 standart deviation:  0.25970785482
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[1 0 0 0 0]

In [45]:
#Create a custom dtype that describes a color as four unisgned bytes (RGBA)
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])

#Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 
r = np.dot(np.ones((5,3)), np.ones((3,2)))
print(r)

#Extract the integer part of a random array using different methods 
s = np.random.uniform(0,10,10)
print(s)
print(np.floor(s))
print(np.ceil(s))
print(s.astype(int))
print(np.trunc(s)) #truncate a matrix

#Sort an array
#Python use Timsort algorithm
t = np.random.random(5)
print("t: ", t)
t.sort()
print("sorted t: ", t)

#Consider two random array A anb B, check if they are equal
A = np.random.randint(0,3,6,"int")
B = np.random.randint(0,3,6)
equal = np.allclose(A,B)
print(equal)

#Create random vector of size 10 and replace the maximum value by 0 
v = np.random.random(10)
v[v.argmax()] = 0
print(v)

#Make an array read-only
u = np.zeros(10)
u.flags.writeable = False #to have 6 flags options
u[0] = 1



[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]
[ 2.00798789  2.17957976  9.67759296  7.18906961  4.82367447  2.75323134
  9.33544289  1.07846118  5.3252294   3.79725644]
[ 2.  2.  9.  7.  4.  2.  9.  1.  5.  3.]
[  3.   3.  10.   8.   5.   3.  10.   2.   6.   4.]
[2 2 9 7 4 2 9 1 5 3]
[ 2.  2.  9.  7.  4.  2.  9.  1.  5.  3.]
t:  [ 0.54420757  0.62529723  0.20456799  0.19020287  0.51815934]
sorted t:  [ 0.19020287  0.20456799  0.51815934  0.54420757  0.62529723]
False
[ 0.90727335  0.04159988  0.51020876  0.80082746  0.          0.42125832
  0.74207872  0.45441675  0.46600381  0.95780564]


ValueError: assignment destination is read-only

In [49]:
#Make QR factorization
M = np.random.randn(5,4)
q, r = np.linalg.qr(M)
print(q)
print(r)
#check M=qr or not
np.allclose(M, np.dot(q,r))

[[-0.56365082 -0.03797013 -0.72813386  0.25648648]
 [-0.16088054 -0.19100488  0.45301187 -0.06513977]
 [ 0.31811661 -0.49683994 -0.4143367  -0.68314462]
 [-0.73129903 -0.29938966  0.2957504  -0.36873627]
 [-0.14289418  0.7909433  -0.07387921 -0.57211755]]
[[-2.54806081  0.33146086 -1.44062148  0.45976334]
 [ 0.         -1.69420861 -0.78457541 -0.8329533 ]
 [ 0.          0.         -1.29720041 -0.33625447]
 [ 0.          0.          0.          0.44805897]]


True

In [55]:
#inverse of a matrix
N = np.array([[1,2,3], [3,1,2], [3,2,1]])
print(N)
np.linalg.inv(N)

[[1 2 3]
 [3 1 2]
 [3 2 1]]


array([[-0.25      ,  0.33333333,  0.08333333],
       [ 0.25      , -0.66666667,  0.58333333],
       [ 0.25      ,  0.33333333, -0.41666667]])

In [56]:
#N.x = y
y = np.array([1,0,2])
q1,r1 = np.linalg.qr(N)
z = np.dot(q1.T, y)